import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="px-8 md:px-32 lg:px-48 xl:px-64 2xl:px-96 py-4">
          <div className="flex justify-around">
            <Link href="/" className="hover:bg-blue-500 hover:text-white px-4 py-1 rounded">Home</Link>
            <Link href="https://www.meetup.com/awskcug/" className="hover:bg-blue-500 hover:text-white px-4 py-1 rounded">Meetup</Link>
            <Link href="https://www.meetup.com/awskcug/members/" className="hover:bg-blue-500 hover:text-white px-4 py-1 rounded">Members</Link>
          </div>          
        </nav>
        {children}
      </body>
    </html>
  );
}
