name: GHA

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.3
      - run: |
          cd src
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync ./src/out s3://awskcug-web
